# Autogenerated with SMOP version 
# /Users/lalit/anaconda/bin/smop create_piv_simulation_parameters_02.m

from __future__ import division
try:
    from runtime import *
except ImportError:
    from smop.runtime import *

def create_piv_simulation_parameters_02_(*args,**kwargs):
    varargin = cellarray(args)
    nargin = 0-[].count(None)+len(args)

    piv_simulation_parameters=copy_(struct)
    piv_simulation_parameters.lens_design=struct
    piv_simulation_parameters.lens_design.focal_length=105000.0
    piv_simulation_parameters.lens_design.aperture_f_number=8.0
    piv_simulation_parameters.lens_design.object_distance=700000.0
    piv_simulation_parameters.camera_design=struct
    piv_simulation_parameters.camera_design.pixel_pitch=17
    piv_simulation_parameters.camera_design.x_pixel_number=1024
    piv_simulation_parameters.camera_design.y_pixel_number=1024
    piv_simulation_parameters.camera_design.pixel_bit_depth=10
    piv_simulation_parameters.camera_design.pixel_gain=[]
    piv_simulation_parameters.camera_design.x_camera_angle=- 25 * pi / 180
    piv_simulation_parameters.camera_design.y_camera_angle=- 0 * pi / 180
    piv_simulation_parameters.particle_field=struct
    piv_simulation_parameters.particle_field.generate_particle_field_images=true
    piv_simulation_parameters.particle_field.data_directory=char('')
    piv_simulation_parameters.particle_field.data_filename_prefix=char('particle_data_frame')
    piv_simulation_parameters.particle_field.frame_vector=arange_(1,2)
    piv_simulation_parameters.particle_field.particle_number=500000.0
    piv_simulation_parameters.particle_field.lightray_number_per_particle=10000.0
    piv_simulation_parameters.particle_field.lightray_process_number=1000000.0
    piv_simulation_parameters.particle_field.pixel_gain=30
    piv_simulation_parameters.particle_field.gaussian_beam_fwhm=730.0
    piv_simulation_parameters.particle_field.perform_mie_scattering=true
    piv_simulation_parameters.particle_field.medium_refractive_index=1.333
    piv_simulation_parameters.particle_field.particle_refractive_index=1.57
    piv_simulation_parameters.particle_field.particle_diameter_mean=27
    piv_simulation_parameters.particle_field.particle_diameter_std=5
    piv_simulation_parameters.particle_field.particle_diameter_number=27
    piv_simulation_parameters.particle_field.particle_diameter_cdf_threshhold=0.01
    piv_simulation_parameters.particle_field.mie_scattering_angle_number=128
    piv_simulation_parameters.particle_field.beam_propogation_vector=[0,1,0]
    piv_simulation_parameters.particle_field.beam_wavelength=0.532
    piv_simulation_parameters.calibration_grid=struct
    piv_simulation_parameters.calibration_grid.generate_calibration_grid_images=true
    piv_simulation_parameters.calibration_grid.grid_point_diameter=3200.0
    piv_simulation_parameters.calibration_grid.x_grid_point_spacing=15000.0
    piv_simulation_parameters.calibration_grid.y_grid_point_spacing=15000.0
    piv_simulation_parameters.calibration_grid.x_grid_point_number=11
    piv_simulation_parameters.calibration_grid.y_grid_point_number=11
    piv_simulation_parameters.calibration_grid.calibration_plane_number=7
    piv_simulation_parameters.calibration_grid.calibration_plane_spacing=1000.0
    piv_simulation_parameters.calibration_grid.particle_number_per_grid_point=1000.0
    piv_simulation_parameters.calibration_grid.lightray_number_per_particle=500.0
    piv_simulation_parameters.calibration_grid.lightray_process_number=1000000.0
    piv_simulation_parameters.calibration_grid.pixel_gain=25
    piv_simulation_parameters.output_data=struct
    piv_simulation_parameters.output_data.particle_image_directory=char('')
    piv_simulation_parameters.output_data.calibration_grid_image_directory=char('')
    return piv_simulation_parameters
